name: Deploy to Development Environment

on:
  push:
    branches: 
      - dev
  workflow_dispatch:  # Permite ejecutar manualmente desde la interfaz de GitHub

jobs:
  deploy:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Si tienes dependencias de desarrollo adicionales
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          fi

      - name: Install custom dependencies
        run: |
          # Si está en un repositorio Git privado
          git clone https://github.com/MR34Z1r0/aje-cdk-libs.git
          cd aje-cdk-libs
          pip install -e .
          cd ..
          
      - name: Install custom dependencies
        run: |
          # Si está en un repositorio Git privado
          git clone https://github.com/MR34Z1r0/aje-libs.git
          cd aje-cdk-libs
          pip install -e .
          cd ..
        
      - name: Install AWS CDK
        run: npm install -g aws-cdk
        
      - name: Configure environment (DEV)
        run: |
          # Copia el archivo de variables de entorno para desarrollo
          cp dev.env .env
          echo "Usando configuración de DESARROLLO"
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_AWS_REGION }}
          
      - name: CDK Bootstrap (if needed)
        run: cdk bootstrap
        
      - name: Deploy with CDK
        run: cdk deploy --all --require-approval never
        
      - name: Notify successful deployment
        if: success()
        run: |
          echo "✅ Despliegue a DESARROLLO completado exitosamente."
          # Aquí podrías añadir notificaciones (Slack, email, etc.)