name: Deploy to Production Environment

on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    name: Deploy to PRODUCTION
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install custom dependencies
        run: |
          # Si está en un repositorio Git privado
          git clone https://github.com/MR34Z1r0/aje-cdk-libs.git
          cd aje-cdk-libs
          pip install -e .
          cd ..
          
      - name: Install custom dependencies
        run: |
          # Si está en un repositorio Git privado
          git clone https://github.com/MR34Z1r0/aje-libs.git
          cd aje-cdk-libs
          pip install -e .
          cd ..
          
      - name: Install AWS CDK
        run: npm install -g aws-cdk
        
      - name: Configure environment (PROD)
        run: |
          # Copia el archivo de variables de entorno para producción
          cp prod.env .env
          echo "⚠️ Usando configuración de PRODUCCIÓN"
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.PROD_AWS_REGION }}
          
      - name: CDK Bootstrap (if needed)
        run: cdk bootstrap
        
      - name: Deploy with CDK
        run: cdk deploy --all --require-approval never
        
      - name: Notify successful deployment
        if: success()
        run: |
          echo "✅ ATENCIÓN: Despliegue a PRODUCCIÓN completado exitosamente."
          # Aquí podrías añadir notificaciones (Slack, email, etc.)