name: Deploy to Development

on:
  push:
    branches: [ dev ]
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install aws-cdk-lib
          
      - name: Install AWS CDK
        run: npm install -g aws-cdk
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_AWS_REGION }}
          
      - name: CDK Bootstrap (si es necesario)
        run: cdk bootstrap
        
      - name: CDK Deploy to DEV
        run: cdk deploy --all --require-approval never -c environment=dev